#!/usr/bin/env python3
# File: `LabSync-Unix`
import os
import sys
import runpy

project_root = os.path.dirname(os.path.abspath(__file__))
src_path = os.path.join(project_root, "src")

if src_path not in sys.path:
    sys.path.insert(0, src_path)

if __name__ == "__main__":
    # run the module that contains main() and starts the QApplication
    runpy.run_module("core.labsync", run_name="__main__")
